site_name: Monstache
site_url: https://rwynn.github.io/monstache-site/
site_description: Realtime sync from MongoDB to Elasticsearch.
site_author: Monstache Team
docs_dir: src
site_dir: docs
repo_url: https://github.com/rwynn/monstache-site/
edit_uri: edit/master/src/
copyright: Copyright &copy; 2016-2018 Ryan Wynn
google_analytics: ['UA-113057322-1', 'rwynn.github.io']
extra_css:
    - css/extra.css
nav:
    - "Home": index.md
    - "Getting Started": start.md
    - "Configuration": config.md
    - "Advanced": advanced.md
    - "About": about.md
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list
theme:
    name: mkdocs
    highlightjs: True
    hljs_style: atelier-cave-light
    hljs_languages:
        - go
